FROM python:3.10.13-slim-bookworm

WORKDIR /app

RUN pip install flask

ENV FLASK_APP ./dummy_autoupdate/dummy_autoupdate.py
ENV FLASK_ENV development

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "9012"]
